.TH pgs-chroma 1
.SH NAME
pgs-chroma - modify the colours of PGS image-based subtitles
.SH SYNOPSIS
.B pgs-chroma [\fBoptions...\fR] <\fBinput\fR> <\fBoutput\fR>
.SH OPTIONS
.TP
.BR \-f " " \fIFILTER\fR
Set the filter to be used. Default: "clipped".
.TP
.BR \-h
Show help message and exit.
.TP
.BR \-v
Print version information and exit.
